### ISSUE TITLE
U01: As a registered user I want to be able to search for a specific course by its name so that I easily and quickly find the course community I am looking for.

### ISSUE THREAD

**Issue by Taremeh** [The-Agile-Avengers/icu-connect-frontend#1]
Requirement: The platform should allow users to search for different course communities.

# Development Tasks

- [ ] The-Agile-Avengers/icu-connect-frontend#23
- [ ] The-Agile-Avengers/icu-connect-frontend#24
- [x] The-Agile-Avengers/icu-connect-backend#11
- [x] The-Agile-Avengers/icu-connect-backend#40
- [x] #145
