### ISSUE TITLE
U07: As a registered user, I want to create course related posts such as questions so that I and the other members of the community can exchange information.

### ISSUE THREAD

**Issue by Mariinja** [The-Agile-Avengers/icu-connect-frontend#11]
Requirement: Users should be able to create course related posts (e.g. questions, comments).

# Development Tasks

- [ ] The-Agile-Avengers/icu-connect-frontend#34
- [ ] The-Agile-Avengers/icu-connect-frontend#35
- [ ] The-Agile-Avengers/icu-connect-frontend#36
- [ ] The-Agile-Avengers/icu-connect-backend#5
- [ ] The-Agile-Avengers/icu-connect-backend#36
