### ISSUE TITLE
U08: As a registered user, I want to answer or comment on a post from another member in one of the course pages so that I can help this student or take part in a discussion.

### ISSUE THREAD

**Issue by Mariinja** [The-Agile-Avengers/icu-connect-frontend#12]
Requirement: Users should be able to answer/comment below posts (in the form of communication threads).

# Development Tasks

- [ ] The-Agile-Avengers/icu-connect-frontend#37
- [ ] The-Agile-Avengers/icu-connect-frontend#38
- [ ] The-Agile-Avengers/icu-connect-frontend#39
- [ ] The-Agile-Avengers/icu-connect-backend#20
- [ ] The-Agile-Avengers/icu-connect-backend#19
