### ISSUE TITLE
U09: As a registered user, I want rate courses based on a star rating so that I can give feedback.

### ISSUE THREAD

**Issue by Mariinja** [The-Agile-Avengers/icu-connect-frontend#13]
Requirement: The platform should allow users to rate courses using a 5-star rating.

# Development Tasks

- [ ] The-Agile-Avengers/icu-connect-frontend#40
- [ ] The-Agile-Avengers/icu-connect-frontend#41
- [ ] The-Agile-Avengers/icu-connect-frontend#42
- [ ] The-Agile-Avengers/icu-connect-backend#3
- [ ] The-Agile-Avengers/icu-connect-backend#2
- [ ] The-Agile-Avengers/icu-connect-backend#42
