### ISSUE TITLE
U12: As a registered user, I want to like ratings, I deem useful so that to express my support to ratings I deem useful.

### ISSUE THREAD

**Issue by Mariinja** [The-Agile-Avengers/icu-connect-frontend#15]
Requirement: The platform should allow users to like ratings they perceived to be helpful.

# Development Tasks

- [ ] The-Agile-Avengers/icu-connect-backend#23
- [ ] The-Agile-Avengers/icu-connect-backend#24
- [ ] The-Agile-Avengers/icu-connect-backend#25
- [x] The-Agile-Avengers/icu-connect-frontend#98
- [x] The-Agile-Avengers/icu-connect-frontend#99
- [ ] The-Agile-Avengers/icu-connect-backend#101
- [ ] The-Agile-Avengers/icu-connect-frontend#194

**Comment by Mariinja** [comment]
everything closed
