### ISSUE TITLE
Technical Debt: When creating a course the teacher should be selectable / searchable

### ISSUE THREAD

**Issue by Mariinja** [The-Agile-Avengers/icu-connect-frontend#163]
- [ ] The-Agile-Avengers/icu-connect-backend#81
- [ ] The-Agile-Avengers/icu-connect-frontend#165
- [ ] #167
- [ ] The-Agile-Avengers/icu-connect-backend#82
