### ISSUE TITLE
U14: As an unregistered user, I want to register a new account so that I can log in and access the platform

### ISSUE THREAD

**Issue by Mariinja** [The-Agile-Avengers/icu-connect-frontend#17]
Requirement: The platform should allow users to register and login with a username and
password.

# Development Tasks
- [x] The-Agile-Avengers/icu-connect-backend#16
- [x] The-Agile-Avengers/icu-connect-backend#17
- [x] The-Agile-Avengers/icu-connect-backend#18
- [x] #102
- [x] #103
- [x] #104
