### ISSUE TITLE
U16: As a registered user, I want to add or change personal information such as my profile avatar, my study area and my username so that I can communicate to other users more about myself.

### ISSUE THREAD

**Issue by Mariinja** [The-Agile-Avengers/icu-connect-frontend#18]
Requirement: Users should be able to edit their profiles with personal information, such as profile picture, username and study area.

# Development Tasks

- [x] The-Agile-Avengers/icu-connect-backend#35
- [x] The-Agile-Avengers/icu-connect-backend#34
- [x] The-Agile-Avengers/icu-connect-frontend#107
- [x] The-Agile-Avengers/icu-connect-frontend#108
- [x] The-Agile-Avengers/icu-connect-frontend#161
- [x] The-Agile-Avengers/icu-connect-backend#91
- [x] The-Agile-Avengers/icu-connect-backend#92
- [x] The-Agile-Avengers/icu-connect-backend#93
