### ISSUE TITLE
U17: As a registered user, I want to upload learning materials, exam protocols, or other course related documents so that other students can benefit from my learning materials and course notes.

### ISSUE THREAD

**Issue by Mariinja** [The-Agile-Avengers/icu-connect-frontend#19]
Requirement: Users should be able to upload documents into course communities.

# Development Tasks
- [x] The-Agile-Avengers/icu-connect-backend#28
- [x] The-Agile-Avengers/icu-connect-backend#29
- [x] The-Agile-Avengers/icu-connect-backend#12
- [x] #109
- [x] #110
