### ISSUE TITLE
U15: As a registered user I want to login using a username and password so that I am able to post new messages and course ratings which only registered users can do

### ISSUE THREAD

**Issue by Taremeh** [The-Agile-Avengers/icu-connect-frontend#53]
# Development Tasks
- [x] The-Agile-Avengers/icu-connect-backend#13
- [x] The-Agile-Avengers/icu-connect-backend#14
- [x] The-Agile-Avengers/icu-connect-backend#15
- [x] The-Agile-Avengers/icu-connect-frontend#105
- [x] The-Agile-Avengers/icu-connect-frontend#106
- [x] The-Agile-Avengers/icu-connect-backend#55
