### ISSUE TITLE
U03: As a registered user, I want to be able to see the content of a joined course community so that I can read the posts and take part in discussions.

### ISSUE THREAD

**Issue by Mariinja** [The-Agile-Avengers/icu-connect-frontend#7]
Requirement: The social network should allow a user to view his/her joined course communities.

# Development Tasks

- [x] The-Agile-Avengers/icu-connect-frontend#27
- [x] The-Agile-Avengers/icu-connect-backend#9
- [x] The-Agile-Avengers/icu-connect-backend#44
- [x] #124
- [ ] #139
